version: 2
jobs:
  test_fooddelivery_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/fooddelivery/requirements.txt
            echo "../../../../packages/fooddelivery" >> env/lib/python3.8/site-packages/extra.pth
            python packages/fooddelivery/fooddelivery/main.py
            py.test -vv packages/fooddelivery/codetesting

workflows:
  version: 2
  test-all:
    jobs:
      - test_fooddelivery_model
